import dbgtools.commands.domalloc
import dbgtools.commands.dofree
import dbgtools.commands.heapbase
import dbgtools.commands.breaknew
import dbgtools.commands.breakpie
import dbgtools.commands.asanok
import dbgtools.commands.asanviz
import dbgtools.commands.v8heap
import dbgtools.commands.gadgetsearch
import dbgtools.commands.libcbase
import dbgtools.commands.traceheap
import dbgtools.commands.tracer
import dbgtools.commands.heaplookup
import dbgtools.commands.pwndump
import dbgtools.commands.getoffsets
